# Numpy

In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5]

In [3]:
arr=np.array(lst)

In [4]:
type(arr)

numpy.ndarray

In [5]:
arr

array([1, 2, 3, 4, 5])

In [8]:
arr1=np.array([[1,2,3],[1,2,3]])

In [9]:
arr.ndim

1

In [10]:
arr1.ndim

2

In [11]:
arr1

array([[1, 2, 3],
       [1, 2, 3]])

In [13]:
mat=np.matrix(lst)

In [14]:
np.asarray(lst)

array([1, 2, 3, 4, 5])

- matrix is one type of array it will not convert into array 

In [16]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
a=arr # shallow copy (copying refernce)

In [19]:
a

array([1, 2, 3, 4, 5])

In [20]:
arr

array([1, 2, 3, 4, 5])

In [21]:
a[0]=100

In [22]:
a

array([100,   2,   3,   4,   5])

In [23]:
arr

array([100,   2,   3,   4,   5])

In [28]:
b=np.copy(arr) # deep copy (only values got copied)

In [25]:
b[0]=200

In [26]:
b

array([200,   2,   3,   4,   5])

In [27]:
arr

array([100,   2,   3,   4,   5])

# numpy functions

check row i index with j col index

fromfunction - we can generate data

In [29]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [30]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [32]:
list([ i*i for i in range(5)])

[0, 1, 4, 9, 16]

In [33]:
iterable =(i*i for i in range(5))

In [34]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring("23 45 67",sep=' ')

array([23., 45., 67.])

In [36]:
arr

array([100,   2,   3,   4,   5])

In [38]:
arr1

array([[1, 2, 3],
       [1, 2, 3]])

In [39]:
arr1.ndim

2

In [41]:
arr.size # number of elements

5

In [42]:
arr1.size

6

In [43]:
arr1.shape

(2, 3)

In [45]:
arr.shape # 1 dim

(5,)

# numpy range functions

In [46]:
list(range(5))

[0, 1, 2, 3, 4]

In [47]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- range function only takes integers as input

In [48]:
list(range(0.4,12))

TypeError: 'float' object cannot be interpreted as an integer

# arange

- to overcome it we can arange function

In [49]:
np.arange(0.4,10)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

In [54]:
np.arange(0.4,10,1) #(start,stop,diff)

array([0.4, 1.4, 2.4, 3.4, 4.4, 5.4, 6.4, 7.4, 8.4, 9.4])

# linspace

In [53]:
np.linspace(1,5,20) #(start,stop,no of elements)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

# logspace

In [55]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

# zeros

In [56]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [57]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [59]:
np.zeros((3,4,2)) # 3dim matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [60]:
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

# ones

In [61]:
np.ones(1)

array([1.])

In [63]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [64]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# empty

In [66]:
np.empty((1,2))

array([[ 4.92581899e-88, -1.26593783e-36]])

# eye

- diagonal elemets are 1 and no of rows== no of columns

In [67]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [68]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
arr2 = np.array(np.eye(3))

In [70]:
import pandas as pd

In [71]:
pd.DataFrame(arr2)

0    1    2
0  1.0  0.0  0.0
1  0.0  1.0  0.0
2  0.0  0.0  1.0

# random.rand
- it generates required ndim array but without any particular std and mean

In [72]:
np.random.rand(2,3)

array([[0.04501684, 0.97119238, 0.14697689],
       [0.54764704, 0.97667926, 0.58009306]])

# random.randn
- it is similar to random.rand function but it follows std 1 and mean=0

In [73]:
np.random.randn(2,3)

array([[ 0.76513551,  0.22068109, -0.76637809],
       [-2.26647404, -0.24640375,  1.09938267]])

# random.randint
- it generates numbers between givne range

In [75]:
arr2=np.random.randint(1,5,(3,3))

In [76]:
arr2.shape

(3, 3)

In [77]:
arr2.reshape(9,1)

array([[3],
       [3],
       [3],
       [2],
       [3],
       [4],
       [1],
       [4],
       [4]])

In [78]:
arr3 =np.random.randint(1,5,(3,4))

In [79]:
arr3.shape

(3, 4)

In [80]:
arr3

array([[3, 3, 3, 1],
       [1, 3, 2, 2],
       [2, 4, 1, 1]])

In [82]:
arr3.reshape(2,6)

array([[3, 3, 3, 1, 1, 3],
       [2, 2, 2, 4, 1, 1]])

In [83]:
arr3.reshape((2,2,3))

array([[[3, 3, 3],
        [1, 1, 3]],

       [[2, 2, 2],
        [4, 1, 1]]])

In [84]:
arr1=np.random.randint(1,10,(5,6))

In [85]:
arr1>8

array([[False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]])

In [86]:
arr1[arr1>8]

array([9])

In [87]:
arr1

array([[2, 2, 8, 3, 5, 2],
       [2, 5, 6, 5, 2, 1],
       [3, 1, 3, 8, 1, 2],
       [9, 4, 4, 6, 6, 7],
       [1, 8, 1, 1, 8, 4]])

In [88]:
arr1[0,[0,1]]

array([2, 2])

In [89]:
np.log(arr1)

array([[0.69314718, 0.69314718, 2.07944154, 1.09861229, 1.60943791,
        0.69314718],
       [0.69314718, 1.60943791, 1.79175947, 1.60943791, 0.69314718,
        0.        ],
       [1.09861229, 0.        , 1.09861229, 2.07944154, 0.        ,
        0.69314718],
       [2.19722458, 1.38629436, 1.38629436, 1.79175947, 1.79175947,
        1.94591015],
       [0.        , 2.07944154, 0.        , 0.        , 2.07944154,
        1.38629436]])

In [90]:
np.exp(arr1)

array([[7.38905610e+00, 7.38905610e+00, 2.98095799e+03, 2.00855369e+01,
        1.48413159e+02, 7.38905610e+00],
       [7.38905610e+00, 1.48413159e+02, 4.03428793e+02, 1.48413159e+02,
        7.38905610e+00, 2.71828183e+00],
       [2.00855369e+01, 2.71828183e+00, 2.00855369e+01, 2.98095799e+03,
        2.71828183e+00, 7.38905610e+00],
       [8.10308393e+03, 5.45981500e+01, 5.45981500e+01, 4.03428793e+02,
        4.03428793e+02, 1.09663316e+03],
       [2.71828183e+00, 2.98095799e+03, 2.71828183e+00, 2.71828183e+00,
        2.98095799e+03, 5.45981500e+01]])

In [91]:
arr1

array([[2, 2, 8, 3, 5, 2],
       [2, 5, 6, 5, 2, 1],
       [3, 1, 3, 8, 1, 2],
       [9, 4, 4, 6, 6, 7],
       [1, 8, 1, 1, 8, 4]])

In [92]:
arr1.T

array([[2, 2, 3, 9, 1],
       [2, 5, 1, 4, 8],
       [8, 6, 3, 4, 1],
       [3, 5, 8, 6, 1],
       [5, 2, 1, 6, 8],
       [2, 1, 2, 7, 4]])

In [93]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 2.82842712, 1.73205081, 2.23606798,
        1.41421356],
       [1.41421356, 2.23606798, 2.44948974, 2.23606798, 1.41421356,
        1.        ],
       [1.73205081, 1.        , 1.73205081, 2.82842712, 1.        ,
        1.41421356],
       [3.        , 2.        , 2.        , 2.44948974, 2.44948974,
        2.64575131],
       [1.        , 2.82842712, 1.        , 1.        , 2.82842712,
        2.        ]])

In [94]:
arr1+2

array([[ 4,  4, 10,  5,  7,  4],
       [ 4,  7,  8,  7,  4,  3],
       [ 5,  3,  5, 10,  3,  4],
       [11,  6,  6,  8,  8,  9],
       [ 3, 10,  3,  3, 10,  6]])

In [95]:
arr1*2

array([[ 4,  4, 16,  6, 10,  4],
       [ 4, 10, 12, 10,  4,  2],
       [ 6,  2,  6, 16,  2,  4],
       [18,  8,  8, 12, 12, 14],
       [ 2, 16,  2,  2, 16,  8]])

In [96]:
np.max(arr1)

9

In [97]:
np.min(arr1)

1

# Array manipulation

In [98]:
arr=np.random.randint(1,10,(4,4))

In [99]:
arr

array([[5, 6, 4, 5],
       [6, 6, 7, 8],
       [3, 2, 6, 6],
       [3, 4, 3, 2]])

In [100]:
arr.reshape(8,2)

array([[5, 6],
       [4, 5],
       [6, 6],
       [7, 8],
       [3, 2],
       [6, 6],
       [3, 4],
       [3, 2]])

In [101]:
arr.T

array([[5, 6, 3, 3],
       [6, 6, 2, 4],
       [4, 7, 6, 3],
       [5, 8, 6, 2]])

In [102]:
arr.flatten()

array([5, 6, 4, 5, 6, 6, 7, 8, 3, 2, 6, 6, 3, 4, 3, 2])

In [103]:
np.expand_dims(arr,axis=1)

array([[[5, 6, 4, 5]],

       [[6, 6, 7, 8]],

       [[3, 2, 6, 6]],

       [[3, 4, 3, 2]]])

In [104]:
np.expand_dims(arr,axis=0)

array([[[5, 6, 4, 5],
        [6, 6, 7, 8],
        [3, 2, 6, 6],
        [3, 4, 3, 2]]])

# squeeze

In [106]:
data=np.array([[1],[2],[3]])

In [107]:
np.squeeze(data)

array([1, 2, 3])

# repeat

In [110]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

# roll

In [112]:
data

array([[1],
       [2],
       [3]])

In [111]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

# diag

In [113]:
np.diag(np.array([1,23]))

array([[ 1,  0],
       [ 0, 23]])

# Binary operations on array

In [114]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [115]:
arr1

array([[8, 1, 4, 5],
       [6, 1, 6, 2],
       [1, 6, 7, 8]])

In [116]:
arr1+arr2

array([[17,  9, 10,  6],
       [ 7,  8, 12, 10],
       [ 5, 14,  9, 11]])

In [117]:
arr1*arr2

array([[72,  8, 24,  5],
       [ 6,  7, 36, 16],
       [ 4, 48, 14, 24]])

In [118]:
arr1/arr2

array([[0.88888889, 0.125     , 0.66666667, 5.        ],
       [6.        , 0.14285714, 1.        , 0.25      ],
       [0.25      , 0.75      , 3.5       , 2.66666667]])

In [119]:
arr1-arr2

array([[-1, -7, -2,  4],
       [ 5, -6,  0, -6],
       [-3, -2,  5,  5]])

In [120]:
arr1**arr2

array([[134217728,         1,      4096,         5],
       [        6,         1,     46656,       256],
       [        1,   1679616,        49,       512]])

In [121]:
~arr1

array([[-9, -2, -5, -6],
       [-7, -2, -7, -3],
       [-2, -7, -8, -9]])

In [122]:
arr1>arr2

array([[False, False, False,  True],
       [ True, False, False, False],
       [False, False,  True,  True]])

# numpy string functions 

In [123]:
arr=np.array(['kee','rio'])

In [124]:
arr

array(['kee', 'rio'], dtype='<U3')

In [125]:
np.char.upper(arr)

array(['KEE', 'RIO'], dtype='<U3')

In [126]:
np.char.capitalize(arr)

array(['Kee', 'Rio'], dtype='<U3')

In [127]:
np.char.title(arr)

array(['Kee', 'Rio'], dtype='<U3')

# numpy mathematical funcitons

In [128]:
arr1

array([[8, 1, 4, 5],
       [6, 1, 6, 2],
       [1, 6, 7, 8]])

In [129]:
np.sin(arr1)

array([[ 0.98935825,  0.84147098, -0.7568025 , -0.95892427],
       [-0.2794155 ,  0.84147098, -0.2794155 ,  0.90929743],
       [ 0.84147098, -0.2794155 ,  0.6569866 ,  0.98935825]])

In [130]:
np.cos(arr1)

array([[-0.14550003,  0.54030231, -0.65364362,  0.28366219],
       [ 0.96017029,  0.54030231,  0.96017029, -0.41614684],
       [ 0.54030231,  0.96017029,  0.75390225, -0.14550003]])

In [131]:
np.tan(arr1)

array([[-6.79971146,  1.55740772,  1.15782128, -3.38051501],
       [-0.29100619,  1.55740772, -0.29100619, -2.18503986],
       [ 1.55740772, -0.29100619,  0.87144798, -6.79971146]])

In [132]:
np.log10(arr1)

array([[0.90308999, 0.        , 0.60205999, 0.69897   ],
       [0.77815125, 0.        , 0.77815125, 0.30103   ],
       [0.        , 0.77815125, 0.84509804, 0.90308999]])

In [133]:
np.exp(arr1)

array([[2.98095799e+03, 2.71828183e+00, 5.45981500e+01, 1.48413159e+02],
       [4.03428793e+02, 2.71828183e+00, 4.03428793e+02, 7.38905610e+00],
       [2.71828183e+00, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03]])

In [134]:
np.power(arr1,2)

array([[64,  1, 16, 25],
       [36,  1, 36,  4],
       [ 1, 36, 49, 64]], dtype=int32)

In [135]:
np.mean(arr1)

4.583333333333333

In [136]:
np.median(arr1)

5.5

In [137]:
np.std(arr1)

2.5967394084804805

In [138]:
np.var(arr1)

6.743055555555556

In [139]:
np.min(arr1)

1

In [140]:
np.max(arr1)

8

# numpy airthmetic operations

In [141]:
arr1

array([[8, 1, 4, 5],
       [6, 1, 6, 2],
       [1, 6, 7, 8]])

In [142]:
arr2

array([[9, 8, 6, 1],
       [1, 7, 6, 8],
       [4, 8, 2, 3]])

In [143]:
arr1-arr2

array([[-1, -7, -2,  4],
       [ 5, -6,  0, -6],
       [-3, -2,  5,  5]])

In [144]:
np.subtract(arr1,arr2)

array([[-1, -7, -2,  4],
       [ 5, -6,  0, -6],
       [-3, -2,  5,  5]])

In [145]:
np.multiply(arr1,arr2)

array([[72,  8, 24,  5],
       [ 6,  7, 36, 16],
       [ 4, 48, 14, 24]])

In [146]:
np.mod(arr1,arr2)

array([[8, 1, 4, 0],
       [0, 1, 0, 2],
       [1, 6, 1, 2]])

In [147]:
np.power(arr1,arr2)

array([[134217728,         1,      4096,         5],
       [        6,         1,     46656,       256],
       [        1,   1679616,        49,       512]])

In [148]:
np.sqrt(arr1)

array([[2.82842712, 1.        , 2.        , 2.23606798],
       [2.44948974, 1.        , 2.44948974, 1.41421356],
       [1.        , 2.44948974, 2.64575131, 2.82842712]])